### ISSUE TITLE
Upgrade to Laravel 6.x

### ISSUE THREAD

**Issue by connecteev** [LaravelDaily/QuickAdminPanel-Issues-Ideas-Discussions#14]
Upgrade to Laravel 6.x

**Comment by PovilasKorop** [comment]
@connecteev what do you mean? We support 6.x for new panels. And if you want to upgrade old 5.x panel to 6.x then Clone it and choose version 6.

**Comment by connecteev** [comment]
@PovilasKorop thanks, I didnt know v6 was supported. Is there a way to migrate to v6 on an existing panel, or is cloning the only option?

**Comment by PovilasKorop** [comment]
@connecteev no, only cloning
