### ISSUE TITLE
massDestroy should be authorized

### ISSUE THREAD

**Issue by hvj78** [LaravelDaily/QuickAdminPanel-Issues-Ideas-Discussions#17]
I am using AJAX Datatables and Multitenancy modules (builder id: 22948)

In the generated Controllers, the massDestroy method do not contain the authorization (the first line in the other controller methods):

abort_if(Gate::denies('..._delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

Manually can be easily fixed, but the generator should put it there.

**Comment by mc0de** [comment]
Hi, since it is post request it is handled in same way as store or update methods, via request authorize() method.

there's an example of some crud, please check `app/Http/Requests` folder

 ```php
class MassDestroyBookRequest extends FormRequest
{
    public function authorize()
    {
        abort_if(Gate::denies('book_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return true;
    }

    public function rules()
    {
        return [
            'ids'   => 'required|array',
            'ids.*' => 'exists:books,id',
        ];
    }
}

**Comment by mc0de** [comment]
and controller auto injects this request

```php
    public function massDestroy(MassDestroyBookRequest $request)
    {
        Book::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }

**Comment by hvj78** [comment]
Hi!
Thanks for the detailed explanaiton
On the other hand, it is misleading, that for some actions like Store, Update, massDestroy, authorization is happening under Requests\...Request.php, for other actions the same functionality is happening in the Controller. I would keep a functionality implemented either here or there but not mixed, to make generated the code more clear and maintainable for newbies to quickadminpanel like me :)
Thank you,
János
